### ISSUE TITLE
Serializer do the primary key as String

### ISSUE THREAD

**Issue by dakiesse** [duyluonglc/lucid-mongo#106]
Hey! I have met it where I tried to use relations like that:

```
async controllerMethod({auth}) {
  const user = await auth.getUser()
  return user.accounts().fetch()
}
```
The variable 'user' has property _id as string and It has made via https://github.com/duyluonglc/lucid-mongo/blob/develop/src/LucidMongo/Serializers/LucidMongoSerializer.js#L118
Why did you decide to make it?

**Comment by duyluonglc** [comment]
Hi @dakiesse, nice question
Yes I convert the `_id` to string because the Adonis session does not allow store `ObjectID` to session, see the issue here https://github.com/duyluonglc/lucid-mongo/issues/56

so if you have realtion example: `user` has many `account` (the `account` document has `user_id` field), you should define the `user_id` field as `ObjectID` the query will convert `string` back to `ObjectID` before execute
see here to know how to define a field as `ObjectID`:
https://github.com/duyluonglc/lucid-mongo#field-type

Please let me know if you have better solution. Thanks

**Comment by ketz86** [comment]
Hi @duyluonglc , sorry for writing here, but after using your package in combination with [adonis-acl](https://github.com/enniel/adonis-acl) I got some issues related to the string casting of the _id field.

After some investigation i found that when the authenticated user is retrieved from the session and the primary key get casted to String, some of the relations in the acl models doesn't work.

I tried replacing your serializer with a custom one(which is basically a copy of yours with only the String casting removed ) and everything seems to work without any problem.

So I investigated a little more and I found that the ObjectID type was added to adonis-session not long ago [https://github.com/adonisjs/adonis-session/pull/3](https://github.com/adonisjs/adonis-session/pull/3).

Does that pr solve the need for the String casting?

**Comment by duyluonglc** [comment]
Hi @ketz86 
Nice to see what you investigated.
Can you fork this repo then remove all String() pattern in the serializer?
`https://github.com/duyluonglc/lucid-mongo/blob/develop/src/LucidMongo/Serializers/LucidMongoSerializer.js`
Make sure you pass the test with session issue :)
Your PR is welcome

**Comment by slampenny** [comment]
This has been closed, but is the PR merged?

**Comment by duyluonglc** [comment]
The is no PR but have one commit ;)
