### ISSUE TITLE
Logging in wrong user!!!

### ISSUE THREAD

**Issue by rykerparker** [duyluonglc/lucid-mongo#158]
Would any of you have a clue why adonis logs in the wrong user no matter what login method I use whether its loginViaId() or Login the user model directly or even attempt(). I'm using lucid-mongo and for some reason no matter what data im submitting adonis logs into the first user in the database very strange glitch.
heres some code
...
config/auth
```
session: {
    serializer: 'LucidMongo',
    model: 'App/Models/User',
    scheme: 'session',
    uid: 'email',
    password: 'password'
  },
...
UserController.js
const user = new User();

      user.username = request.input('username')
      user.email = request.input('email')
      user.password = await Hash.make(request.input('password'))

      await user.save();
      await auth.loginViaId(user._id)

**Comment by duyluonglc** [comment]
@rykerparker thanks for report
After checked I see the problem come from adonis-session. the id stored in session is not instance of mongodb ObjectID. That's why the query is correct but result is not
![image](https://user-images.githubusercontent.com/14918470/48307075-f8a17580-e577-11e8-8c01-95b6e2890b38.png)
